---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create directory"
  become_user: true
  file:
    path: ~/udapeople/
    state: directory


- name: "deploy backend"
  become_user: true
  unarchive:
    src: /artifact.tar.gz
    dest: ~/udapeople/

# - name: "copy files from CircleCI to server"
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

# - name: Creates directory
#   file:
#     path: ~/backend_server
#     state: directory

# - name: Copy index test page
#   template:
#     src: "/artifact.tar.gz"
#     dest: "~/backend_server/"

- name: "use pm2 to run the node server"
  shell: |
    cd ~/udapeople/
    npm i
    pm2 start npm -- run "start:dev"

# - name: Executing node
#   shell: |
#     pm2 start ~/backend_server/index.js -f
