---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "Create directory"
  become: true
  file:
    path: ~/udapeople/
    state: directory

- name: "install npm packages"
  become: true
  command: npm install --force
  args:
    chdir: ~/udapeople/

- name: "compile npm packages"
  become: true
  command: npm run build
  args:
    chdir: ~/udapeople/

- name: "deploy backend"
  become: true
  unarchive:
    src: /artifact.tar.gz
    dest: ~/udapeople/

- name: "run backend"
  become: true
  shell: |
    cd ~/udapeople/
    npm i
    pm2 start npm -- run start

# - name: "copy backend file"
#   become: true
#   copy:
#     src: /root/project/backend
#     dest: /root
#     force: no

- name: "start server"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: ~/udapeople/dist